os: linux
dist: bionic
language: ruby
services: docker

addons:
  apt:
    sources:
      - sourceline: 'deb https://packages.chef.io/repos/apt/stable bionic main'
        key_url: 'https://packages.chef.io/chef.asc'
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  global:
    - KITCHEN_LOCAL_YAML=kitchen.dokken.yml
    - CHEF_LICENSE=accept
  jobs:
    - INSTANCE=default-amazonlinux-1
    - INSTANCE=default-amazonlinux-2
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-centos-8
    - INSTANCE=default-debian-8
    - INSTANCE=default-debian-9
    - INSTANCE=default-debian-10
    - INSTANCE=default-fedora-30
    - INSTANCE=default-fedora-31
    - INSTANCE=default-fedora-latest
    # - INSTANCE=default-opensuse-leap-15
    - INSTANCE=default-oraclelinux-6
    - INSTANCE=default-oraclelinux-7
    - INSTANCE=default-oraclelinux-8
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-ubuntu-1910
    - INSTANCE=default-ubuntu-2004

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: kitchen verify ${INSTANCE}

jobs:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
