name: kitchen

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

jobs:
  dokken:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2
          - centos-8
          - debian-9
          - fedora-34
          - oraclelinux-8
          - ubuntu-20.04
        chef_version: [16, 17]
        suite: [default]
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Install Chef
      uses: actionshub/chef-install@master
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@master
      with:
        suite: ${{ matrix.suite }}
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        CHEF_VERSION: ${{ matrix.chef_version }}
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
  