name: kitchen

on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]

env:
  CHEF_LICENSE: accept-no-persist
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - amazonlinux-2023
          - centos-stream-10
          - debian-12
          - fedora-40
          - oraclelinux-9
          - ubuntu-2404
        workstation_version:
          - '24.12.1073'
          - '25.5.1084'
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install Chef
      uses: actionshub/chef-install@main
      with:
        version: ${{ matrix.workstation_version }}
    - name: Cookstyle
      run: cookstyle --display-cop-names --extra-details
    - name: Rspec
      run: chef exec rspec
    - name: Test-Kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: default
        os: ${{ matrix.os }}
      env:
        KITCHEN_LOCAL_YAML: kitchen.dokken.yml
