name: chef supermarket
on:
  release:
    types: [published]

jobs:
  share:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Chef Supermarket Share
        uses: afaundez/chef-supermarket@master
        with:
          key: ${{ secrets.supermarketKey }}
